apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-cm
data:
  # ATTACKED_HOST: http://kube-znn:8080
  # ATTACKED_HOST: http://nginx-ingress.default.svc
  ATTACKED_HOST: http://pynn.default.svc:8080
  