apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-master
  name: locust-master
spec:
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9646"
    spec:
      containers:
      - image: containersol/locust_exporter
        name: locust-exporter
        ports:
        - containerPort: 9646
          name: exporter
      - image: cmendes/locust
        name: locust-master
        env:
          - name: ATTACKED_HOST
            valueFrom:
              configMapKeyRef:
                name: locust-cm
                key: ATTACKED_HOST
          - name: LOCUST_MODE
            value: MASTER
        volumeMounts:
          - mountPath: /locust
            name: locust-scripts
        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-1
        - containerPort: 8089
          name: web-ui
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
      nodeSelector:
        localhost.k8s.io/layer: "testing"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-slave
  name: locust-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-slave
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      containers:
      - image: cmendes/locust
        name: locust-slave
        env:
          - name: ATTACKED_HOST
            valueFrom:
              configMapKeyRef:
                name: locust-cm
                key: ATTACKED_HOST
          - name: LOCUST_MODE
            value: SLAVE
          - name: LOCUST_MASTER
            value: locust-master
        volumeMounts:
          - mountPath: /locust
            name: locust-scripts
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
      nodeSelector:
        localhost.k8s.io/layer: "testing"  