apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpLocust, TaskSet

    def get_news(l):
        l.client.get("/news.php", verify=False)

    class UserBehavior(TaskSet):
        tasks = {get_news: 1}

    class WebsiteUser(HttpLocust):
        task_set = UserBehavior
