apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-proxy
  labels:
    app: k8s-proxy
spec:
  selector:
    matchLabels:
      app: k8s-proxy
  template:
    metadata:
      labels:
        app: k8s-proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
    spec:
      serviceAccountName: admin-user
      volumes:
      - name: k8s-envoy-config
        configMap:
          name: k8s-envoy-config
      containers:
      - name: k8s-proxy
        image: envoyproxy/envoy:v1.11.2
        imagePullPolicy: Always
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy.yaml"]
        ports:
        - name: http
          containerPort: 8081
        - name: metrics
          containerPort: 8084
        volumeMounts:
        - name: k8s-envoy-config
          mountPath: /etc/envoy.yaml
          subPath: envoy.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-proxy
  labels:
    app: k8s-proxy
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8084
    targetPort: metrics
    protocol: TCP
  selector:
    app: k8s-proxy