apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: probes
data:
  probes.yaml: |
    probes:
      CustomMetricsProbe:
        alias: kube-znn.latency.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: br.unifor.kubow.probes.PrometheusProbe
          period: 5000
          args.length: 4
          args.0: "default"
          args.1: "kube-znn"
          args.2: "latency"
          args.3: "histogram_quantile(0.99, rate(caddy_http_request_duration_seconds_bucket{namespace=\"default\",host=~\"localhost\"}[30s]))"

      DeploymentPropertiesProbe:
        alias: deployments.default.kube-znn.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: br.unifor.kubow.probes.DeploymentInfoProbe
          period: 5000
          args.length: 2
          args.0: "default"
          args.1: "kube-znn"
