apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: strategies
data:
  strategies.s: |
    module kubow.strategies;
    import model "KubeZnnSystem:Acme" { KubeZnnSystem as M, KubernetesFam as K };
    import lib "tactics.s";

    define boolean cHiRespTime = M.kubeZnnS.latency > M.MAX_RESPTIME;
    define boolean highTraffic = M.kubeZnnS.traffic > 300;

    define boolean cLoRespTime = M.kubeZnnS.latency < M.MIN_RESPTIME;
    define boolean canAddPod = M.kubeZnnD.maxReplicas > M.kubeZnnD.desiredReplicas;
    define boolean canRemovePod = M.kubeZnnD.minReplicas < M.kubeZnnD.desiredReplicas;

    strategy ReduceRespTime [ highTraffic ] {
      t0: (highTraffic) -> addReplicas(1) @[10000] {
        t0a: (success) -> done;
      }
    }